version: "3.8"

services:
  frontend:
    container_name: mylog-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - .:/mylog-frontend
      - /mylog-frontend/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    working_dir: /mylog-frontend
    command: yarn dev
